import { CALENDLY_URL } from "@/lib/site-config";

export const defaultSiteContent = {
  brandName: "Lumivale",
  logoText: "L",
  logoUrl: "",
  heroHeading: "Light up your growth with",
  heroHighlight: "simple execution systems",
  heroDescription: "Lumivale helps early-stage teams find the channels that actually bring customers, then turns those channels into clear, repeatable growth actions.",
  heroPrompt: "Ready to grow?",
  heroButtonText: "Book a call",
  heroButtonUrl: CALENDLY_URL,
  aboutEyebrow: "About Lumivale",
  aboutHeading: "Small team. Clear direction. Shared momentum.",
  aboutDescription: "We bring strategy, creative execution, and outreach together to help early-stage teams find their next growth channel.",
  aboutApproachHeading: "Close to your team. Focused on the work.",
  aboutApproachDescription: "We keep priorities clear, test channels with purpose, and turn what works into repeatable actions. Practical support, from the first conversation to the next campaign.",
  aboutTeamHeading: "Meet the founders.",
  aboutTeamDescription: "Three perspectives, working toward the same goal: helping your business move forward.",
  aboutFounder1Name: "John Doe",
  aboutFounder1Role: "Founder, Growth Strategy",
  aboutFounder1Image: "/founders/about-placeholder.jpg",
  aboutFounder1Summary: "Shapes focused growth plans, keeps priorities clear, and helps founders turn early traction into repeatable customer activity.",
  aboutFounder2Name: "John Doe",
  aboutFounder2Role: "Founder, Creative Operations",
  aboutFounder2Image: "/founders/about-placeholder.jpg",
  aboutFounder2Summary: "Leads creator, content, and campaign execution with a practical eye for speed, consistency, and brand fit.",
  aboutFounder3Name: "John Doe",
  aboutFounder3Role: "Founder, Outreach Systems",
  aboutFounder3Image: "/founders/about-placeholder.jpg",
  aboutFounder3Summary: "Builds lean outbound systems across LinkedIn and email so early teams can test channels without unnecessary complexity.",
  resultsEyebrow: "What we deliver",
  resultsHeading: "Growth support in numbers.",
  resultsMetric1Value: "30-60",
  resultsMetric1Label: "Short-form videos per month",
  resultsMetric2Value: "5-10",
  resultsMetric2Label: "Creator collaboration deals",
  resultsMetric3Value: "15-20",
  resultsMetric3Label: "LinkedIn connections per day",
  resultsMetric4Value: "60",
  resultsMetric4Label: "B2B emails per day",
  footerCtaPrompt: "Start here",
  footerCtaHeading: "Light up the next growth channel for your brand.",
  footerCtaButtonText: "Book a call",
  footerCtaButtonUrl: CALENDLY_URL,
  footerBrandName: "Lumivale",
  footerTagline: "Light up your growth.",
  footerHomeLabel: "Home",
  footerHomeUrl: "/",
  footerAboutLabel: "About",
  footerAboutUrl: "/about",
  footerBlogsLabel: "Blogs",
  footerBlogsUrl: "/blogs",
  footerContactHeading: "Get in touch",
  footerEmail: "kenny.lumivale@gmail.com",
  footerLinkedinUrl: "https://www.linkedin.com/company/lumivale-agency/",
  footerSiteLabel: "lumivale.net",
  footerBottomText: "Simple, affordable growth support for early-stage teams.",
};
export type SiteContent = typeof defaultSiteContent;
