import { CALENDLY_URL } from "@/lib/site-config";

export const defaultSiteContent = {
  brandName: "Lumivale",
  logoText: "L",
  logoUrl: "",
  heroHeading: "Light up your growth with",
  heroHighlight: "simple execution systems",
  heroDescription: "Lumivale helps early-stage teams find the channels that actually bring customers, then turns those channels into clear, repeatable growth actions.",
  heroPrompt: "Ready to grow?",
  heroButtonText: "Book a call",
  heroButtonUrl: CALENDLY_URL,
  resultsEyebrow: "The results",
  resultsHeading: "Growth you can measure.",
  resultsMetric1Value: "—",
  resultsMetric1Label: "Result 1 placeholder",
  resultsMetric2Value: "—",
  resultsMetric2Label: "Result 2 placeholder",
  resultsMetric3Value: "—",
  resultsMetric3Label: "Result 3 placeholder",
  resultsMetric4Value: "—",
  resultsMetric4Label: "Result 4 placeholder",
  footerCtaPrompt: "Start here",
  footerCtaHeading: "Light up the next growth channel for your brand.",
  footerCtaButtonText: "Book a call",
  footerCtaButtonUrl: CALENDLY_URL,
  footerBrandName: "Lumivale",
  footerTagline: "Light up your growth.",
  footerHomeLabel: "Home",
  footerHomeUrl: "/",
  footerAboutLabel: "About",
  footerAboutUrl: "/about",
  footerBlogsLabel: "Blogs",
  footerBlogsUrl: "/blogs",
  footerContactHeading: "Get in touch",
  footerEmail: "kenny.lumivale@gmail.com",
  footerLinkedinUrl: "https://www.linkedin.com/company/lumivale-agency/",
  footerSiteLabel: "lumivale.net",
  footerBottomText: "Simple, affordable growth support for early-stage teams.",
};
export type SiteContent = typeof defaultSiteContent;
